# Generated by Django 4.1.7 on 2023-05-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=3)),
                ('user_score', models.IntegerField()),
            ],
        ),
    ]
